import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Header from "@/app/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row lg:flex-col">
          <Header
            pages={[
              {
                text: "Home",
                link: "/home",
              },
              {
                text: "Suspense",
                link: "/suspense",
              },
              {
                text: "Counter",
                link: "/counter",
              },
              {
                text: "Products",
                link: "/products",
              },
            ]}
          />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
